### ISSUE TITLE
gist about switch playtime

### ISSUE THREAD

**Issue by zuanzuanshao** [matchai/awesome-pinned-gists#23]
Could have a gist what about switch playtime leaderboard?

**Comment by sciencepal** [comment]
Hey, can you give more references .. what is switch and what features would you want?

**Comment by ukyzr** [comment]
like steam playtime
![image](https://user-images.githubusercontent.com/43691054/88149022-0f93d880-cc32-11ea-9776-3906f49fe2c6.png)

**Comment by ChrisCarini** [comment]
@rsuxwvilc - Is it safe to assume you mean [Nintendo Switch](https://www.nintendo.com/switch/)? Do you have any links to APIs and/or libraries that can query for similar data?

**Comment by Swilder-M** [comment]
> Could have a gist what about switch playtime leaderboard?

Hi, you can now use this repository https://github.com/Swilder-M/nintendo-switch-box to implement.
