### ISSUE TITLE
My Pinned gist was removed from the list

### ISSUE THREAD

**Issue by Aveek-Saha** [matchai/awesome-pinned-gists#41]
I had raised a PR(#31) to include two pined gists: spotify-box and blog-box. I see now that spotify-box has been removed in this commit: https://github.com/matchai/awesome-pinned-gists/pull/31/commits/5cb7f37d510bf882345dd3c49561680934f326c2

Can you please fix this and add spotify-box back to the list? I see there is another spotify-box now, but since my PR was aproved first it should take precedence

**Comment by ChrisCarini** [comment]
Looks like this was fixed in #43 - closing issue.
