### ISSUE TITLE
Is the repo matchai/awesome-pinned-gists inactive?

### ISSUE THREAD

**Issue by ChrisCarini** [matchai/awesome-pinned-gists#54]
Hi @matchai !

Thank you for compiling this repo. I noticed that there are several PRs that have not been addressed in a while, but you appear to be active on GitHub.

**❓ Question:** Is this repo still maintained/active?

**If not**, would you mind taking a look at the outstanding PRs?
**If so**, I'd be happy to help maintain this repository and look at incoming PRs if you are open to it. I've already done a pass on all the open PRs that are not my own.

**Comment by matchai** [comment]
Hey @ChrisCarini! 👋
Unfortunately, I've got my hands pretty full these days and this repo has been neglected as a result. Since you offered, I've gone ahead and added you as a maintainer to the repo. Feel free to merge any PRs abide by the code of conduct, contributing guidelines, and spirit of the repo! 😄

**Comment by ChrisCarini** [comment]
> Unfortunately, I've got my hands pretty full these days and this repo has been neglected as a result.

Understandable :)

> Since you offered, I've gone ahead and added you as a maintainer to the repo.

Cool, thank you!

> Feel free to merge any PRs abide by the code of conduct, contributing guidelines, and spirit of the repo! 😄

Sounds good! I've gone ahead and either merged or reviewed the outstanding PRs, and gone through and done a pass on the existing issues. I also added a pull request template to the repo to help standardize PRs when folks open them.

❓ One last question since I have your attention 😄 - are you open to me making other changes/improvements to the repo, or would you prefer I just simply try to review/merge in PRs as they come?

I am asking, because I have a few ideas like below, but would want your general blessing/approval before I charge off and make issues / changes to the repo that are atypical.

1. [Alpha-sorting the sections](https://github.com/matchai/awesome-pinned-gists/pull/55) to make it easier for folks to identify where to make additions
2. Programatically generating the list from a json file that is part of the repo (in hopes of standardizing / structuring things a bit more)

**Comment by matchai** [comment]
>  Are you open to me making other changes/improvements to the repo, or would you prefer I just simply try to review/merge in PRs as they come?

Absolutely! You're welcome to make structural changes to the repo's README as long as they abide by the guidelines imposed by the Awesome List project.

> 2. Programatically generating the list from a json file that is part of the repo
I believe this might be in opposition to the Awesome List guidelines, here: https://github.com/sindresorhus/awesome/blame/main/pull_request_template.md#L62
